# Generated by Django 5.2.14 on 2026-05-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='jefesoporte',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='jefesoporte',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='last_login',
        ),
    ]
