# Generated by Django 6.0.5 on 2026-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_domicilio_empresa_pais_usuario_domicilio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
