# Generated by Django 6.0.5 on 2026-06-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_empresa_alter_infoticket_prioridad_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador de Empresa'), ('cliente', 'Cliente'), ('soporte', 'Soporte'), ('jefe', 'Jefe Soporte')], max_length=20),
        ),
    ]
