# Generated by Django 6.0.5 on 2026-06-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_autorizado_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador de Empresa'), ('cliente', 'Cliente'), ('soporte', 'Soporte'), ('jefe', 'Jefe de Soporte')], max_length=20),
        ),
    ]
