# Generated by Django 6.0.5 on 2026-06-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_feedback_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='horario_egreso',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horario_ingreso',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
