# Generated by Django 6.0.5 on 2026-06-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='require_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_cliente', 'Administrador de Empresa'), ('cliente', 'Cliente'), ('soporte', 'Soporte'), ('jefe', 'Jefe de Soporte')], max_length=20),
        ),
    ]
