# Generated by Django 6.0.5 on 2026-06-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_horario_egreso_usuario_horario_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dias_laborales',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
