# Generated by Django 6.0.5 on 2026-06-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_dias_laborales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackplatform',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedbackservice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedbacksupportinternal',
            options={},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='plan',
            field=models.CharField(choices=[('GRATIS', 'Gratis'), ('BASICO', 'Básico'), ('PREMIUM', 'Premium')], default='GRATIS', max_length=20),
        ),
    ]
