# Generated by Django 6.0.5 on 2026-06-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_require_password_change_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoticket',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=20, null=True),
        ),
    ]
