# Generated by Django 6.0.5 on 2026-06-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_infoticket_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoticket',
            name='numero_ticket_empresa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
